// نام فارسی رمزارزهای پرکاربرد (کلید = id در CoinGecko)؛ برای بقیه نام انگلیسی نمایش داده می‌شود.
export const CRYPTO_FA: Record<string, string> = {
  bitcoin: 'بیت‌کوین',
  ethereum: 'اتریوم',
  tether: 'تتر',
  ripple: 'ریپل',
  binancecoin: 'بایننس کوین',
  solana: 'سولانا',
  'usd-coin': 'یو‌اس‌دی کوین',
  dogecoin: 'دوج‌کوین',
  cardano: 'کاردانو',
  tron: 'ترون',
  'the-open-network': 'تون‌کوین',
  chainlink: 'چین‌لینک',
  'avalanche-2': 'آوالانچ',
  'shiba-inu': 'شیبا اینو',
  stellar: 'استلار',
  litecoin: 'لایت‌کوین',
  'bitcoin-cash': 'بیت‌کوین کش',
  polkadot: 'پولکادات',
  monero: 'مونرو',
  uniswap: 'یونی‌سواپ',
  dai: 'دای',
  cosmos: 'کازماس',
  'ethereum-classic': 'اتریوم کلاسیک',
  near: 'نیر',
  aptos: 'آپتوس',
  filecoin: 'فایل‌کوین',
  vechain: 'وی‌چین',
  algorand: 'الگوراند',
  eos: 'ایاس',
  tezos: 'تزوس',
  dash: 'دش',
  zcash: 'زیکش',
  pepe: 'پپه',
  'matic-network': 'پالیگان',
  'polygon-ecosystem-token': 'پالیگان',
  'internet-computer': 'اینترنت کامپیوتر',
  'hedera-hashgraph': 'هدرا',
  sui: 'سویی',
  'pax-gold': 'پکس گلد',
  'wrapped-bitcoin': 'رپد بیت‌کوین',
  'staked-ether': 'استیکد اتر',
}
